// SOMA Nutrition Implementation Brief Part B, item 3: PROGRESSIVE lifecycle
// engine. Deterministic, same "code decides the number, AI never judges the
// gate" principle as targets.js/practiceTest.js - this module never calls
// Claude. A SESSION quest (cardio/gym/recovery/practice-test/job-match/
// job-application, all untouched by this file) is generate -> one evidence
// submit -> done; a PROGRESSIVE quest accumulates several submissions across
// one day before it resolves. quest.lifecycleType distinguishes the two;
// only "progressive" quests carry a quest.progressive object.

const PROGRESSIVE_METRICS = ["calories", "protein", "carbohydrates", "fat"];

function num(v) {
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}

// Fresh state for a brand-new PROGRESSIVE quest, e.g. generated by
// generateQuest or /api/meta/start for the Nutrition tool.
function initProgressiveState({ requiredContributions, primaryMetric, targetValue }) {
  const reqC = num(requiredContributions);
  const target = num(targetValue);
  return {
    requiredContributions: reqC != null && reqC > 0 ? Math.round(reqC) : 3,
    completedContributions: 0,
    primaryMetric: PROGRESSIVE_METRICS.includes(primaryMetric) ? primaryMetric : "protein",
    targetValue: target != null && target > 0 ? target : 60,
    currentValue: 0,
    evidenceComplete: false,
    // Compliance (evidenceComplete) and target-achievement (targetMet) are
    // tracked as SEPARATE booleans (brief item 8 - "never merged") - a user
    // who logs every meal but stays under their protein target is a
    // fundamentally different outcome from one who just didn't log, even
    // though both currently read "not yet met".
    targetMet: false,
    status: "ACTIVE",
  };
}

// One food_entries row folded into the running total - called once per
// logged meal (search-based or photo-based, both normalize to the same
// entry shape before reaching here, see server/nutritionEntry.js).
// COMPLETED fires the moment both booleans go true, same day, no waiting
// for a day boundary (brief item 8: "on all evidence-complete+target-met ->
// auto COMPLETED, no manual confirm").
function applyContribution(progressive, entry) {
  const completedContributions = progressive.completedContributions + 1;
  const currentValue = progressive.currentValue + (num(entry[progressive.primaryMetric]) || 0);
  const evidenceComplete = completedContributions >= progressive.requiredContributions;
  const targetMet = currentValue >= progressive.targetValue;
  return {
    ...progressive,
    completedContributions, currentValue, evidenceComplete, targetMet,
    status: evidenceComplete && targetMet ? "COMPLETED" : "ACTIVE",
  };
}

// Lazy end-of-day resolution (same idiom as the kondisi daily reset / Decay
// lazy check elsewhere in this codebase - no cron infra in this app, so a
// PROGRESSIVE quest is only ever resolved the next time something reads its
// state after the quest's `date` has rolled past). Only meaningful when
// status is still "ACTIVE" (COMPLETED already resolved itself mid-day).
function evaluateEndOfDay(progressive) {
  if (progressive.status !== "ACTIVE") return progressive;
  if (progressive.evidenceComplete && progressive.targetMet) return { ...progressive, status: "COMPLETED" };
  if (progressive.evidenceComplete) return { ...progressive, status: "ATTEMPTED" };
  return { ...progressive, status: "INCOMPLETE" };
}

const METRIC_LABEL = { calories: "Kalori", protein: "Protein", carbohydrates: "Karbo", fat: "Lemak" };
const METRIC_UNIT = { calories: "kkal", protein: "g", carbohydrates: "g", fat: "g" };

// Home quest card live-progress line (brief item 7's own example: "Meals
// 2/3 · Protein 61/90g").
function progressLabel(progressive) {
  const p = progressive;
  return `Meals ${p.completedContributions}/${p.requiredContributions} · ${METRIC_LABEL[p.primaryMetric]} ${Math.round(p.currentValue)}/${p.targetValue}${METRIC_UNIT[p.primaryMetric]}`;
}

module.exports = { PROGRESSIVE_METRICS, initProgressiveState, applyContribution, evaluateEndOfDay, progressLabel };
